//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuznetsov_IS_21_3_Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public string Facts { get; set; }
        public string ImageSRC { get; set; }
        public string SoundSRC { get; set; }
    }
}
